language: cpp
sudo: false

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.12-linux64.tar.xz
  - tar xf arduino-1.8.12-linux64.tar.xz
  - sudo mv arduino-1.8.12 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

cache:
  directories:
    - ~/arudino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.12"
install:
   - arduino --pref "boardsmanager.additional.urls=https://github.com/esp8266/Arduino/releases/download/2.1.0/package_esp8266com_index.json" --save-prefs
   - arduino --install-library "WolkConnect"
   - arduino --install-boards esp8266:esp8266 --save-prefs
   - arduino --board esp8266:esp8266:generic --save-prefs
   - arduino --pref "compiler.warning_level=all" --save-prefs
notifications:
  email:
    on_success: change
    on_failure: change
