language: cpp
sudo: false

env:
  global:
     - ARDUINO_IDE_VERSION="1.8.12"

before_install:
   - wget -O arduino.tar.xz https://downloads.arduino.cc/arduino-${ARDUINO_IDE_VERSION}-linux64.tar.xz
   - tar xf arduino.tar.xz
   - mv arduino-${ARDUINO_IDE_VERSION} ${HOME}/arduino_ide
   - IDEDIR="${HOME}/arduino_ide"
   - LIBDIR="${IDEDIR}/portable/sketchbook/libraries"
   - mkdir -p "${LIBDIR}"
   - cp -r /home/travis/build/srdjanStankovic/Sonoff-WolkAbout-firmware "${LIBDIR}"
   - export PATH="${IDEDIR}:${PATH}"
   - cd ${IDEDIR}
   - which arduino

install:
  - arduino --install-library "WolkConnect"
  - arduino --install-library "WiFi101"
  - arduino --install-boards "arduino:samd"
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266
  - arduino --pref "compiler.warning_level=all" --save-prefs

cache:
  directories:
    - ~/arudino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true

notifications:
  email:
    on_success: change
    on_failure: change

script:
  - "echo $PWD"
  - cd "/home/travis/build/srdjanStankovic/Sonoff-WolkAbout-firmware/sonoff-wolkabout-firmware"
  - BOARD="esp8266:esp8266:nodemcu"
  - arduino --verbose-build --verify --board ${BOARD} sonoff-wolkabout-firmware.ino

